image: termux/package-builder:latest

stages:
  - build
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: "recursive"

## Copy packages to the build environment.
before_script:
  - |
    echo "[*] Copying packages from './packages' to build environment..."
    for pkg in ./packages/*; do
        if [ -d "./termux-packages/packages/$(basename "$pkg")" ]; then
            echo "[*] Replacing existing $pkg in termux-packages..."
            rm -rf ./termux-packages/packages/$(basename "$pkg")
        fi
        cp -a "$pkg" ./termux-packages/packages/
    done

## Common configuration for all build jobs.
## Variables BINTRAY_* should be unset to
## prevent leaking of sensitive information.
.job_template: &build_job
  stage: build
  script:
    - unset BINTRAY_USERNAME
    - unset BINTRAY_API_KEY
    - unset BINTRAY_GPG_SUBJECT
    - unset BINTRAY_GPG_PASSPHRASE
    - MODIFIED_PACKAGES=$(./scripts/get-modified-packages.sh)
    - cd ./termux-packages
    - |
      for package in $MODIFIED_PACKAGES; do
          ./build-package.sh -q -i -a "$TERMUX_ARCH" "$package"
      done
  retry:
    max: 2
    when:
      - runner_system_failure
      - unknown_failure
  artifacts:
    when: always
    paths:
      - termux-packages/debs

## Building packages for AArch64.
build-aarch64:
  <<: *build_job
  variables:
    TERMUX_ARCH: aarch64

## Building packages for ARM.
build-arm:
  <<: *build_job
  variables:
    TERMUX_ARCH: arm

## Building packages for i686.
build-i686:
  <<: *build_job
  variables:
    TERMUX_ARCH: i686

## Building packages for x86_64.
build-x86_64:
  <<: *build_job
  variables:
    TERMUX_ARCH: x86_64

## Submit build packages to repository.
## This should be executed Only if performing
## builds on branch "master".
upload-packages:
  stage: deploy
  only:
    - android-5@Grimler/termux-root-packages
  script:
    - MODIFIED_PACKAGES=$(./scripts/get-modified-packages.sh)
    - |
      if [ -n "$MODIFIED_PACKAGES" ]; then
          ./scripts/package_uploader.sh --path ./termux-packages/debs $MODIFIED_PACKAGES
      else
          exit 0
      fi
  retry:
    max: 2
    when:
      - runner_system_failure
      - unknown_failure
