language: generic

## Force usage of "Ubuntu Xenial" as on older versions
## program "realpath" is not working for some reason.
os: linux
dist: xenial
services: docker
sudo: required

## Build environment is used as submodule so let
## submodules will be checked out too.
git:
  submodules: true

## Split per-architecture builds into separate jobs.
env:
  matrix:
    - TERMUX_ARCH=aarch64
    - TERMUX_ARCH=arm
    - TERMUX_ARCH=i686
    - TERMUX_ARCH=x86_64

## Build modified packages.
script:
  - unset BINTRAY_USERNAME
  - unset BINTRAY_API_KEY
  - unset BINTRAY_GPG_SUBJECT
  - unset BINTRAY_GPG_PASSPHRASE
  - |
    for package in $(./scripts/get-modified-packages.sh); do
        ./start-builder.sh ./build-package.sh -q -i -a "$TERMUX_ARCH" "$package" || exit 1
    done
